language: java
jdk:
  - oraclejdk7
  - oraclejdk8

before_script:
  - pip install --user codecov

after_success:
  - codecov
  - mvn clean cobertura:cobertura coveralls:report
  - curl http://www.jpm4j.org/install/script > jpmInstall.sh
  - sudo sh jpmInstall.sh
  - sudo jpm install com.codacy:codacy-coverage-reporter:assembly
  - codacy-coverage-reporter -l Java -r target/site/jacoco/jacoco.xml
  