language: java

before_script:
  - pip install --user codecov

after_success:
  - codecov
  - mvn clean cobertura:cobertura coveralls:report
  - curl http://www.jpm4j.org/install/script | sh
  - jpm install com.codacy:codacy-coverage-reporter:assembly
  - export CODACY_PROJECT_TOKEN=%Project_Token%
  - codacy-coverage-reporter -l Java -r coverage.xml
  